# Generated by Django 2.1.7 on 2019-05-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tea', '0004_auto_20190508_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
