# Generated by Django 2.1.7 on 2019-05-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea', '0005_remove_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='typeofitem',
            name='create_at',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='tell',
            field=models.CharField(default='tell', max_length=10),
        ),
    ]
