# Generated by Django 2.1.7 on 2019-05-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tea', '0007_auto_20190509_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='types',
        ),
    ]
